using System.Collections.Generic;
using Newtonsoft.Json;

namespace VolumetricSelection2077.Models.WorldBuilder.Editor;

public class Element
{
    [JsonProperty("modulePath")]
    public string ModulePath { get; set; }
    
    [JsonProperty("name")]
    public string Name { get; set; }

    [JsonProperty("childs")]
    public List<Element> Children { get; set; }
    
    public Element()
    {
        ModulePath = "modules/classes/editor/element";
        Name = "Automatically Generated by VS2077";
        Children = new List<Element>();
    }
}