using System.Collections.Generic;
using Newtonsoft.Json;

namespace VolumetricSelection2077.Models.WorldBuilder.Favorites;

public class FavoritesRoot
{
    [JsonProperty("favorites")]
    public List<Favorite> Favorites { get; set; }

    [JsonProperty("icon")]
    public string Icon { get; set; }
    
    [JsonProperty("name")]
    public string Name { get; set; }
    
    [JsonProperty("grouped")]
    public bool Grouped { get; set; }
    
    [JsonProperty("headerOpen")]
    public bool HeaderOpen { get; set; }
    
    [JsonProperty("virtualGroupsPS")]
    public List<object> VirtualGroupsPS { get; set; }
    
    public FavoritesRoot()
    {
        Favorites = new ();
        Icon = "Group";
        Name = "Generated by VS2077";
        Grouped = false;
        HeaderOpen = false;
        VirtualGroupsPS = new List<object>();
    }
}