using System.Collections.Generic;
using Newtonsoft.Json;
using VolumetricSelection2077.Models.WorldBuilder.Editor;

namespace VolumetricSelection2077.Models.WorldBuilder.Favorites;

public class Favorite
{
    [JsonProperty("name")]
    public string Name { get; set; }
    
    [JsonProperty("tags")]
    public List<string> Tags { get; set; }
    
    [JsonProperty("data")]
    public Positionable Data { get; set; }
    
    [JsonProperty("icon")]
    public string Icon { get; set; }

    public Favorite()
    {
        Name = "Generated by VS2077";
        Tags = new List<string>();
        Data = new Positionable();
        Icon = "Group";
    }
}